### ISSUE TITLE
Annoying custom button.

### ISSUE THREAD

**Issue by agarzon** [plesk/ext-security-advisor#82]
Hi.

Since yesterday Security Advisor is showing in all my Plesks panels a new custom button section in the main page, which by the way its not listed in 
❯ plesk bin custombutton --list

So, there is no way I can hide it and I was forced to uninstall this extension.

I found that new block very, very invasive and annoying block in my panel, and lands there suddenly without any previos warning or consent.

**Comment by batumibiz** [comment]
This button, which can not be removed, really makes nervous.
Please remove it.

**Comment by agarzon** [comment]
To document this better and since I was contacted by Plesk to get more details, here:

### What is wrong and why I'm upset?
____

1. One day there was no custom buttons block in my plesk and then by surprise now I have a massive block (consumes 20% of my screen in vertical) with icon, text, description of something that I can use by going to Extensions and/or add it as custom button if I wanted to. 
2. I have no control on it!, the extension decides to show him self in the panel with no right to decide if I want it to see it there or not.
3. It is in the "custom buttons" block, but in reality it is not a custom button, since you cannot listed by executing: ```plesk bin custombutton --list``` and also cannot be handled by the  "custom buttons" in the panel. 
4. A good example showing how this should be done is the "Mobile Center" extension, this add a real custom button that I can manage. But  "Security Advisor" add it in a more aggressive way.
5. I have 25 installed extensions. **Can you imagine if suddenly all of them decide to do the same?**. 

Don't get me wrong, I like plesk (I've been using it for more than 12 years) and I found "Security Advisor" very useful, but that small decision of adding "**forced**" into the home page and not allowing us any visual control, is a very bad UX and if plesk doesn't take control on it could lead to a disaster where ALL the extensions will want to BE in our home page in the same way: forced.

Remember, people doesn't like "**forced**" stuffs.

### Before:
![before](https://i.imgur.com/CSdQqVN.png)
### After:
![after](https://i.imgur.com/DAPkqFG.png)

Addendum 1: As you can see I'm not the only one concern about it. 
Addendum 2: I'm doing this because I care about Plesk and I want to help.

**Comment by agarzon** [comment]
Reviewing my reports, looks like the already fix this problem, so I'm going to close this issue.
